### PR TITLE
Get Udunits from Github and build with CMake

### LINKED ISSUE #133: UDUNITS 2.2.26 no longer available
Auto build failed:
https://github.com/NOAA-EMC/hpc-stack/pull/132/checks?check_run_id=1595924507

Checking the Unidata website:
https://artifacts.unidata.ucar.edu/service/rest/repository/browse/downloads-udunits/

2.2.28 is the only version available at that location

### PR DESCRIPTION
**Pull request by kgerheiser**
Fixes #133

### CODE REVIEW

File: libs/build_udunits.sh [hunk 1]
```diff
@@ -37,19 +37,22 @@ export FCFLAGS="$FFLAGS"
...
-[[ $enable_shared =~ [yYtT] ]] && shared_flags="" || shared_flags="--disable-shared --enable-static"
+[[ $enable_shared =~ [yYtT] ]] && shared_flags=ON || shared_flags=OFF
 
-../configure --prefix=$prefix $shared_flags
+cmake .. \
+      -DCMAKE_INSTALL_PREFIX=$prefix \
+      -DBUILD_SHARED_LIBS=$shared_flags
 
 make -j${NTHREADS:-4}
-[[ "$MAKE_CHECK" = "YES" ]] && make check
```
Comment (aerorahul) [inline libs/build_udunits.sh:52]: If there is a `ctest` option, we should run that in place of `make check`.  But, a check option should exist.

**Review by aerorahul — CHANGES_REQUESTED** [review]
changes are good, but I have beef against removing the `make check` option. See comment.

File: libs/build_udunits.sh (hunk 1 above)
Comment (kgerheiser) [reply libs/build_udunits.sh:52]: Re-added, but `make test` is the correct option.

It won't run any tests though unless you have some C unit testing framework.

File: libs/build_udunits.sh [hunk 2]
```diff
@@ -37,19 +37,23 @@ export FCFLAGS="$FFLAGS"
...
+[[ "$MAKE_CHECK" = "YES" ]] && make test
```
Comment (aerorahul) [inline libs/build_udunits.sh:56]: Does `make test` run the tests or just builds the executables for the tests?

Comment (kgerheiser) [reply libs/build_udunits.sh:56]: It runs the tests, as is usual with CMake.

```
> make test
Running tests...
Test project /Users/KIG/Desktop/blarn/hpc-stack/pkg/udunits-2.2.26/build
No tests were found!!!
```

File: libs/build_udunits.sh (hunk 1 above)
Comment (aerorahul) [reply libs/build_udunits.sh:52]: how to do that?

Comment (kgerheiser) [reply libs/build_udunits.sh:52]: You need CUnit. When you run CMake it looks for it:

`-- Unable to find CUnit library. Unit-testing not enabled.`

Comment (kgerheiser) [reply libs/build_udunits.sh:52]: The reason I went with CMake was because the source code does not have `configure` file to run. You have to generate it yourself using `autoconf` and if you don't have all those Autotools installed you won't get a `configure` script to run.

Comment (aerorahul) [reply libs/build_udunits.sh:52]: sounds good. thanks for the info.

**Review by aerorahul — APPROVED** [review]
