### PR TITLE
Change source for wgrib2 build

### LINKED ISSUE #294: NCO reported wgrib2 issue in MPMD-style parallel run
**Describe the bug**
Diane Stokes from NCO reported following:
A couple of users have reported trouble running wgrib2 in MPMD-style parallel scripting on Acorn. suspect a conflict with the mpi build of wgrib2 and parallel processing of the scripts that call it. Scott Scallion of MDL suspects the same. He reports:

I am running into an issue submitting an mpmd job of 4 tasks. I get the following errors:

[PE_0]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_0]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_0]:_pmi_init:_pmi_inet_info_init returned -1
Fri Jul 30 14:50:31 2021: [PE_0]:_pmi_init:_pmi_inet_info_init returned -1
app002.acorn.wcoss2.ncep.noaa.gov 1: Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_init:_pmi_inet_info_init returned -1
Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_init:_pmi_inet_info_init returned -1
app002.acorn.wcoss2.ncep.noaa.gov 2: Fri Jul 30 14:50:31 2021: [PE_2]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_2]:_pmi_init:_pmi_inet_info_init returned -1
app002.acorn.wcoss2.ncep.noaa.gov 3: Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_init:_pmi_inet_info_init returned -1
Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_init:_pmi_inet_info_init returned -1

Notice that the error messages for the third task do not match the other three. This is the task that hangs and will not complete, until the job hits the wallclock or is qdel by hand.

/lfs/h1/mdl/ptmp/Scott.Scallion/mpmd-serial-job/wgrib2_mpmd.o35907

Diane highly suspect this is related to MPI build with the wgrib2/2.0.8 module.

**To Reproduce**

**Expected behavior**
Wesley suggested to build the wgrib2 with serial netcdf.

**System:**
WCOSS2 Acron

**Additional context**

### PR DESCRIPTION
**Pull request by kgerheiser**
Take wgrib2 source from the official release and adjust build accordingly.
 
There are many options available for wgrib2 that can be set in the `stack.yaml` file which can take the value `1 = on` or `0 = off`

* netcdf3 
* netcdf4 
* regex 
* tigge 
* ipolates (`0 = off`,  `1 = ip`, `3 = ip2`)
* spectral
* jasper
* ftn_api
* g2clib
* png
* aec
* udf
* openmp

The wgrib2 library is built when `lib: YES`.

Maybe fix #294

### CODE REVIEW

File: libs/build_wgrib2.sh [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+    if [[ `$CC --version` == *"clang"* ]]; then
+        echo "Warning: The Jasper contained in wgrib2 does not build with Clang on macOS"
+        export STACK_wgrib2_jasper=0
+    fi
+fi
+
+COMPILER=$(echo $HPC_COMPILER | cut -d/ -f1)
+if [[ "$COMPILER" == "intel" || "$COMPILER" == "ips" ]]; then
+    export COMP_SYS=intel_linux
+fi
```
Comment (aerorahul) [inline libs/build_wgrib2.sh]: Instead of doing this, can we do:
```suggestion
if [[ $($CC --version | grep Intel) ]]; then
    export COMP_SYS=intel_linux
fi
```

**Comment by aerorahul** [comment]
@kgerheiser 
I assume you will revert all the `build:YES|NO` to their final state when this is ready.
Also, while you are adding a new build script for `wgrib2`, do you want to remove the capability to build it from `build_nceplibs.sh`.  We shouldn't leave two ways to build it to eliminate confusion.  Thoughts?

**Comment by kgerheiser** [comment]
Maybe it should be removed from build NCEPLIBS. My thought on keeping it was to preserve history, at least temporarily. For example, UFS_UTILS currently relies on the config produced by CMake until `FindWGRIB2.cmake` is brought back.

**Review by Hang-Lei-NOAA — APPROVED** [review]
Tested the branch.

**Comment by Hang-Lei-NOAA** [comment]
modulefile path has issue for this wgrib2 installation

**Comment by Hang-Lei-NOAA** [comment]
/apps/ops/prod/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.4/wgrib2/2.0.8.lua:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
help([[]])
conflict("wgrib2")
load("netcdf")
prereq("netcdf")
load("libjpeg")
prereq("libjpeg")
prepend_path("PATH","/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/library/kyle_wgrib2/install/intel/19.1.3.304/cray-mpich/8.1.4/wgrib2/2.0.8/bin")
setenv("wgrib2_ROOT","/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/library/kyle_wgrib2/install/intel/19.1.3.304/cray-mpich/8.1.4/wgrib2/2.0.8")
setenv("wgrib2_VERSION","2.0.8")
setenv("WGRIB2_INC","/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/library/kyle_wgrib2/install/intel/19.1.3.304/cray-mpich/8.1.4/wgrib2/2.0.8/include")
setenv("WGRIB_LIB","/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/library/kyle_wgrib2/install/intel/19.1.3.304/cray-mpich/8.1.4/wgrib2/2.0.8/lib64/libwgrib2.a")
setenv("WGRIB2_LIBAPI","/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/library/kyle_wgrib2/install/intel/19.1.3.304/cray-mpich/8.1.4/wgrib2/2.0.8/lib64/libwgrib2_api.a")
whatis("Name: wgrib2")
whatis("Version: 2.0.8")
whatis("Category: library")
whatis("Description: wgrib2 library")

The actual file was on
ls /lfs/h1/emc/nceplibs/noscrub/Hang.Lei/library/kyle_wgrib2/install/intel-19.1.3.304/wgrib2/2.0.8/

File: .github/workflows/build_macOS.yaml [hunk 2]
```diff
@@ -7,6 +7,7 @@ jobs:
       VERBOSE: 1
     runs-on: macos-10.15
     strategy:
+      fail-fast: false
```
Comment (aerorahul) [inline .github/workflows/build_macOS.yaml]: you want this to continue even if one of the jobs fail?

File: cmake/wgrib2/wgrib2-config.cmake [hunk 3]
```diff
@@ -0,0 +1,21 @@
+find_path (WGRIB2_INCLUDES
+  wgrib2api.mod
+  HINTS $ENV{wgrib2_ROOT}/include)
+
+find_library (WGRIB2_LIBRARIES
+  names libwgrib2.a
+  HINTS $ENV{wgrib2_ROOT}/lib)
```
Comment (aerorahul) [inline cmake/wgrib2/wgrib2-config.cmake:7]: Is it always installed in `lib`? There is no `lib64` variant?

File: cmake/wgrib2/wgrib2-config.cmake [hunk 4]
```diff
@@ -0,0 +1,21 @@
+find_path (WGRIB2_INCLUDES
+  wgrib2api.mod
+  HINTS $ENV{wgrib2_ROOT}/include)
+
+find_library (WGRIB2_LIBRARIES
+  names libwgrib2.a
```
Comment (aerorahul) [inline cmake/wgrib2/wgrib2-config.cmake:6]: What about the `libwgrib2_api.a`?
Does this package not provide that?

File: stack/stack_custom.yaml [hunk 5]
```diff
@@ -13,31 +13,31 @@ cmake:
   version: 3.20.1
 
 jpeg:
-  build: YES
+  build: NO
```
Comment (aerorahul) [inline stack/stack_custom.yaml]: Is there a reason to turn these all to `NO`?

File: stack/stack_mac.yaml [hunk 6]
```diff
@@ -3,7 +3,7 @@ gnu:
   version: 9.3.0
 
 mpi:
-  build: YES
+  build: NO
```
Comment (aerorahul) [inline stack/stack_mac.yaml]: Same question as above.

File: stack/stack_noaa.yaml [hunk 7]
```diff
@@ -4,37 +4,37 @@ cmake:
   version: 3.20.1
 
 jpeg:
-  build: YES
+  build: NO
```
Comment (aerorahul) [inline stack/stack_noaa.yaml]: And here too.

**Review by aerorahul — COMMENTED** [review]
See comments.

File: cmake/wgrib2/wgrib2-config.cmake (hunk 3 above)
Comment (kgerheiser) [reply cmake/wgrib2/wgrib2-config.cmake:7]: Yes

File: stack/stack_custom.yaml (hunk 5 above)
Comment (kgerheiser) [reply stack/stack_custom.yaml]: Was testing the wgrib2 build. Fixed

File: cmake/wgrib2/wgrib2-config.cmake (hunk 4 above)
Comment (kgerheiser) [reply cmake/wgrib2/wgrib2-config.cmake:6]: Good point. I was debating on whether to include it or not since I'm not sure what it does. UFS_UTILS builds fine without it, and I think that's the only application that uses it. I'll go ahead and add it because why not.

File: .github/workflows/build_macOS.yaml (hunk 2 above)
Comment (kgerheiser) [reply .github/workflows/build_macOS.yaml]: I was using this for testing, but I like it. If the MPICH build fails why should OpenMPI not continue?

Comment (aerorahul) [reply .github/workflows/build_macOS.yaml]: That is a valid point.  I was thinking if you will push a change to fix the failure, it will trigger all of them again anyways.  This way, we could save the resources (and the planet), one CI action at a time. 😄

File: cmake/wgrib2/wgrib2-config.cmake (hunk 4 above)
Comment (kgerheiser) [reply cmake/wgrib2/wgrib2-config.cmake:6]: I have included libwgrib2_api

File: cmake/wgrib2/wgrib2-config.cmake [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+  message(STATUS "Unable to locate WGRIB2 library and/or Fortran modules")
+endif()
+
+mark_as_advanced (WGRIB2_INCLUDES WGRIB2_LIBRARIES)
+
+add_library(wgrib2::wgrib2 UNKNOWN IMPORTED)
+set_target_properties(wgrib2::wgrib2 PROPERTIES
+  IMPORTED_LOCATION "${WGRIB2_LIBRARIES}"
+  INTERFACE_INCLUDE_DIRECTORIES "${WGRIB2_INCLUDES}"
+  INTERFACE_LINK_LIBRARIES "${WGRIB2_LIBRARIES}")
```
Comment (aerorahul) [inline cmake/wgrib2/wgrib2-config.cmake:21]: Do we need to create a similar/separate namespace for `wgrib2::wgrib2_api`?
Is there a conflict if we link to `libwgrib2.a` and `libwgrib2_api.a` at the same time?  Because that will happen with what we have here.

Comment (kgerheiser) [reply cmake/wgrib2/wgrib2-config.cmake:21]: I figured this out. `libwgrib2_api.a` is unnecessary. In wgrib2's build everything is put into `libwgrib2.a`. `libwgrib2_api.a` is an intermediate product.

**Review by aerorahul — APPROVED** [review]
Looks good.

**Comment by kgerheiser** [comment]
UFS_UTILS tests pass with this build.
